Deployment restructure
wetfish/danger pull request #1
Opened 2023-01-10 06:01 UTC by g-o-o-s

This PR is to mainline our production deployment changes
It introduces several breaking changes to layout and deployment:

- Restructures the compose stack to have independent mariadb and nginx
- Assumes that it is behind an external traefik
- Supplies the DB hostname via envvars instead of hardcoded
- Sets up autobuilds via actions/ghcr

2023-03-08 09:00 UTC, itsrachelfish requested changes

2023-03-08 09:00 UTC, itsrachelfish commented on .github/workflows/docker-autobuild.yml
> +          context: ./forum/
Why is the forum context being used here?

2023-03-08 15:32 UTC, g-o-o-s commented on .github/workflows/docker-autobuild.yml
> +          context: ./forum/
Must be a ^c^v overlook, it should be just `context: .`

2023-03-08 18:43 UTC, g-o-o-s commented on .github/workflows/docker-autobuild.yml
> +          context: ./forum/
Fixed in [https://github.com/wetfish/danger/pull/1/commits/a70027eb659dde669d61d30bb35bb46a325c1796](https://github.com/wetfish/danger/pull/1/commits/a70027eb659dde669d61d30bb35bb46a325c1796)

2023-06-05 09:29 UTC, itsrachelfish approved these changes
Tested locally, working as expected :tada: 

![image](https://github.com/wetfish/danger/assets/1670549/3e4e5a30-ff56-40d8-a299-ae8825e4003b)

2023-06-05 09:30 UTC, merged